add note for rebase command
theartofeducation/template-repo pull request #11
Opened 2020-10-30 13:57 UTC by Thomas-Jean

2020-10-30 14:06 UTC, theantichris approved these changes

2020-11-02 12:47 UTC, theantichris requested changes

2020-11-02 12:47 UTC, theantichris commented on README.md
> -1. Once your repo is setup [rebase](https://git-scm.com/docs/git-rebase) `develop` on `main` and force push to the `origin`
Replace step 10 with this:

```markdown
1. Rebase `develop` on `main` to ensure that when you create a PR in the future, 
   GitHub will allow it from `develop`
    1. `git rebase -i origin/main`
    1. `git push -f`
```

2020-11-02 14:01 UTC, ryexley approved these changes

2020-11-02 14:18 UTC, theantichris approved these changes

2020-11-02 14:33 UTC, ryexley approved these changes

2020-11-02 19:40 UTC, merged