added steps for branch protection rules
theartofeducation/template-repo pull request #12
Opened 2020-11-03 15:42 UTC by theantichris

2020-11-03 16:01 UTC, ryexley requested changes

2020-11-03 16:01 UTC, ryexley commented on README.md
> +    * You will need to do these steps for each branch
I feel like these two bullets can be combined, and it would make the list below make more sense. Something like: "Follow these steps to setup branch protection in the new repository (manual step):", followed by the numbered list below.

2020-11-03 17:06 UTC, ryexley approved these changes
Thank you. The difference is subtle, but I think much cleaner and easier to read. 👍

2020-11-03 21:49 UTC, Thomas-Jean approved these changes

2020-11-03 21:49 UTC, Thomas-Jean commented on README.md
> +        1. Select ***Dismiss stale pull request approvals when new commits are pushed***
Dismiss stale pull requests create a lot of churn.  As an example, if I reject this and you make a push Bob would need to re-approve even though he gave it a 10-4. I think we may only want this rule on main as that should only have merges and not the back and forth of feature branches. non-blocking

2020-11-04 12:34 UTC, theantichris commented on README.md
> +        1. Select ***Dismiss stale pull request approvals when new commits are pushed***
@Thomas-Jean if I push new changes after Bob has reviewed the PR I would want him to reapprove after looking at the changes. Am I missing something?

2020-11-04 13:19 UTC, merged